"""
Renders pipeline outputs into readable markdown files.

Called at the end of each pipeline run to produce human-readable documents
from the JSON data that the agents generate.
"""

import json
from datetime import date, datetime
from pathlib import Path
from core.config import config


def render_brief(brief: dict, signals: list[dict] = None, findings: dict = None, run_date: date = None):
    """
    Render the daily brief + signal log as a readable markdown file.
    Returns the path to the generated file.
    """
    run_date = run_date or date.today()
    day_name = run_date.strftime("%A, %B %d, %Y")

    lines = []
    lines.append(f"# The Brief — {day_name}")
    lines.append("")
    lines.append("---")
    lines.append("")

    # Tier 1
    tier1 = brief.get("tier_1")
    if tier1:
        lines.append("## The Signal")
        lines.append("")
        lines.append(f"**{tier1.get('headline', '')}**")
        lines.append("")
        lines.append(tier1.get("body", ""))
        lines.append("")
        oq = tier1.get("open_question")
        if oq:
            lines.append(f"→ *{oq}*")
            lines.append("")
    else:
        lines.append("## The Signal")
        lines.append("")
        lines.append("*No signal met the threshold today.*")
        lines.append("")

    lines.append("---")
    lines.append("")

    # Tier 2
    tier2 = brief.get("tier_2")
    if tier2:
        lines.append("## The Bullshit Flag")
        lines.append("")
        lines.append(f"**{tier2.get('headline', '')}**")
        lines.append("")
        lines.append(tier2.get("body", ""))
        lines.append("")
        oq = tier2.get("open_question")
        if oq:
            lines.append(f"→ *{oq}*")
            lines.append("")
    else:
        lines.append("## The Bullshit Flag")
        lines.append("")
        lines.append("*Nothing worth flagging today.*")
        lines.append("")

    lines.append("---")
    lines.append("")

    # Tier 3
    tier3 = brief.get("tier_3")
    if tier3:
        lines.append("## Your World")
        lines.append("")
        lines.append(f"**{tier3.get('headline', '')}**")
        lines.append("")
        lines.append(tier3.get("body", ""))
        lines.append("")
        oq = tier3.get("open_question")
        if oq:
            lines.append(f"→ *{oq}*")
            lines.append("")
    else:
        lines.append("## Your World")
        lines.append("")
        lines.append("*Nothing directly touching your slate today.*")
        lines.append("")

    # Signal Log
    if signals:
        lines.append("---")
        lines.append("")
        lines.append("## Signal Log")
        lines.append("")
        lines.append(f"*{len(signals)} signals ingested on {run_date.isoformat()}*")
        lines.append("")
        for i, s in enumerate(signals, 1):
            sig_type = s.get("signal_type", "unknown")
            headline = s.get("headline", "No headline")
            confidence = s.get("confidence", "?")
            weight = s.get("implication_weight", "?")
            source = s.get("source", "")
            lines.append(f"**{i}. [{sig_type}]** {headline}")
            lines.append(f"   Confidence: {confidence} | Weight: {weight} | Source: {source}")
            implications = s.get("forward_implications", [])
            if implications:
                for imp in implications[:3]:
                    lines.append(f"   → {imp}")
            lines.append("")

    # Findings Summary
    if findings:
        finding_list = findings.get("findings", [])
        if finding_list:
            lines.append("---")
            lines.append("")
            lines.append("## Analysis Summary")
            lines.append("")
            lines.append(f"*{len(finding_list)} findings from analysis*")
            lines.append("")
            for f in finding_list:
                f_type = f.get("type", "unknown")
                headline = f.get("headline", "")
                weight = f.get("implication_weight", "?")
                tier = f.get("tier_recommendation", "none")
                lines.append(f"**[{f_type}]** {headline}")
                lines.append(f"   Weight: {weight} | Tier: {tier}")
                reasoning = f.get("reasoning", "")
                if reasoning:
                    # Truncate long reasoning for the summary
                    preview = reasoning[:300].replace("\n", " ")
                    if len(reasoning) > 300:
                        preview += "..."
                    lines.append(f"   Reasoning: {preview}")
                lines.append("")

    # Footer
    lines.append("---")
    lines.append("")
    lines.append(f"*Generated by Charlie at {datetime.now().strftime('%H:%M:%S')} on {day_name}*")

    # Write file
    md_path = config.briefs_dir / f"{run_date.isoformat()}.md"
    md_path.write_text("\n".join(lines))
    print(f"[Render] Brief written to {md_path}")
    return md_path


def render_thesis_proposal(proposal: dict):
    """
    Render a thesis update proposal as a readable markdown file.
    Returns the path to the generated file.
    """
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    proposed_at = proposal.get("proposed_at", datetime.now().isoformat())

    lines = []
    lines.append("# Thesis Update Proposal")
    lines.append("")
    lines.append(f"*Proposed: {proposed_at}*")
    lines.append("")
    lines.append(f"**Status: {proposal.get('status', 'pending_review')}**")
    lines.append("")

    # Summary
    summary = proposal.get("summary", "")
    if summary:
        lines.append("## Summary")
        lines.append("")
        lines.append(summary)
        lines.append("")

    # Confidence
    confidence = proposal.get("confidence_assessment", "")
    if confidence:
        lines.append(f"**Overall confidence:** {confidence}")
        lines.append("")

    lines.append("---")
    lines.append("")

    # Extensions
    extensions = proposal.get("extensions", [])
    if extensions:
        lines.append("## Proposed Extensions")
        lines.append("")
        lines.append("*New claims or evidence to add to the thesis.*")
        lines.append("")
        for i, ext in enumerate(extensions, 1):
            if isinstance(ext, dict):
                claim = ext.get("claim", ext.get("description", str(ext)))
                evidence = ext.get("evidence", "")
                confidence = ext.get("confidence", "")
                lines.append(f"### Extension {i}")
                lines.append("")
                lines.append(f"**Claim:** {claim}")
                if evidence:
                    lines.append(f"**Evidence:** {evidence}")
                if confidence:
                    lines.append(f"**Confidence:** {confidence}")
                lines.append("")
            else:
                lines.append(f"**{i}.** {ext}")
                lines.append("")

    # Revisions
    revisions = proposal.get("revisions", [])
    if revisions:
        lines.append("---")
        lines.append("")
        lines.append("## Proposed Revisions")
        lines.append("")
        lines.append("*Modifications to existing claims.*")
        lines.append("")
        for i, rev in enumerate(revisions, 1):
            if isinstance(rev, dict):
                before = rev.get("before", rev.get("original_claim", ""))
                after = rev.get("after", rev.get("revised_claim", ""))
                reason = rev.get("reason", rev.get("rationale", ""))
                lines.append(f"### Revision {i}")
                lines.append("")
                if before:
                    lines.append(f"**Before:** {before}")
                if after:
                    lines.append(f"**After:** {after}")
                if reason:
                    lines.append(f"**Rationale:** {reason}")
                lines.append("")
            else:
                lines.append(f"**{i}.** {rev}")
                lines.append("")

    # New Patterns
    new_patterns = proposal.get("new_patterns", [])
    if new_patterns:
        lines.append("---")
        lines.append("")
        lines.append("## Emerging Patterns")
        lines.append("")
        lines.append("*New themes worth watching that are not yet formal thesis claims.*")
        lines.append("")
        for i, pattern in enumerate(new_patterns, 1):
            if isinstance(pattern, dict):
                desc = pattern.get("description", pattern.get("pattern", str(pattern)))
                evidence = pattern.get("evidence", "")
                lines.append(f"**{i}. {desc}**")
                if evidence:
                    lines.append(f"   Evidence: {evidence}")
                lines.append("")
            else:
                lines.append(f"**{i}.** {pattern}")
                lines.append("")

    # Evidence Cited
    evidence_cited = proposal.get("evidence_cited", [])
    if evidence_cited:
        lines.append("---")
        lines.append("")
        lines.append("## Evidence Cited")
        lines.append("")
        for ev in evidence_cited:
            if isinstance(ev, dict):
                lines.append(f"- {ev.get('signal', ev.get('description', str(ev)))}")
            else:
                lines.append(f"- {ev}")
        lines.append("")

    # Watchlist Updates
    watchlist_updates = proposal.get("recommended_watchlist_updates", [])
    if watchlist_updates:
        lines.append("---")
        lines.append("")
        lines.append("## Recommended Watchlist Updates")
        lines.append("")
        for item in watchlist_updates:
            if isinstance(item, dict):
                lines.append(f"- **{item.get('entity', item.get('pattern', ''))}**: {item.get('reason', '')}")
            else:
                lines.append(f"- {item}")
        lines.append("")

    # Footer
    lines.append("---")
    lines.append("")
    lines.append("*To approve this proposal, set status to \"approved\" in the JSON file and run:*")
    lines.append("```")
    lines.append("python -c \"from agents.thesis import apply_proposal; apply_proposal('path/to/proposal.json')\"")
    lines.append("```")
    lines.append("")
    lines.append(f"*Generated by Charlie at {datetime.now().strftime('%H:%M:%S')}*")

    # Write file
    md_path = config.thesis_dir / f"proposal_{timestamp}.md"
    md_path.write_text("\n".join(lines))
    print(f"[Render] Thesis proposal written to {md_path}")
    return md_path