"""
Renders pipeline outputs into readable markdown, HTML, and PDF files.

Called at the end of each pipeline run to produce human-readable documents
from the JSON data that the agents generate.
"""

import json
import subprocess
from datetime import date, datetime
from pathlib import Path
from core.config import config


# ── HTML Template ────────────────────────────────────────────────────────

BRIEF_HTML_TEMPLATE = """<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>The Morning Loaf — {date}</title>
<style>
  * {{ margin: 0; padding: 0; box-sizing: border-box; }}
  body {{ font-family: 'Georgia', serif; background: #fafafa; color: #1a1a1a; line-height: 1.6; }}
  .container {{ max-width: 640px; margin: 0 auto; padding: 40px 24px; }}
  .header {{ border-bottom: 3px solid #1a1a1a; padding-bottom: 16px; margin-bottom: 32px; }}
  .header h1 {{ font-size: 28px; letter-spacing: -0.5px; }}
  .header .date {{ font-size: 14px; color: #666; margin-top: 4px; }}
  .tier {{ margin-bottom: 36px; }}
  .tier-label {{ font-size: 11px; text-transform: uppercase; letter-spacing: 2px; color: #999; margin-bottom: 8px; }}
  .tier h2 {{ font-size: 18px; line-height: 1.4; margin-bottom: 12px; }}
  .tier .body {{ font-size: 15px; color: #333; margin-bottom: 12px; }}
  .tier .question {{ font-size: 14px; color: #666; font-style: italic; padding-left: 16px; border-left: 2px solid #ddd; }}
  .empty {{ font-size: 14px; color: #999; font-style: italic; }}
  .divider {{ border: none; border-top: 1px solid #e0e0e0; margin: 32px 0; }}
  .signal-log {{ margin-top: 40px; border-top: 2px solid #e0e0e0; padding-top: 24px; }}
  .signal-log h3 {{ font-size: 14px; text-transform: uppercase; letter-spacing: 1px; color: #999; margin-bottom: 16px; }}
  .signal {{ margin-bottom: 16px; padding: 12px 16px; background: #f5f5f5; border-radius: 4px; font-size: 13px; }}
  .signal .sig-head {{ font-weight: bold; margin-bottom: 4px; }}
  .signal .sig-meta {{ color: #888; font-size: 12px; }}
  .signal .sig-imp {{ color: #555; font-size: 12px; margin-top: 4px; }}
  .footer {{ margin-top: 40px; padding-top: 16px; border-top: 1px solid #e0e0e0; font-size: 12px; color: #999; }}
  @media print {{
    body {{ background: white; }}
    .container {{ padding: 20px 0; }}
  }}
</style>
</head>
<body>
<div class="container">
  <div class="header">
    <h1>The Morning Loaf</h1>
    <div class="date">{date}</div>
  </div>
  {tiers}
  {signal_log}
  <div class="footer">Generated by Charlie at {timestamp}</div>
</div>
</body>
</html>"""


def _render_tier_html(label: str, tier: dict | None) -> str:
    if not tier:
        return f"""<div class="tier">
  <div class="tier-label">{label}</div>
  <p class="empty">Nothing qualified today.</p>
</div>
<hr class="divider">"""

    headline = tier.get("headline", "")
    body = tier.get("body", "")
    question = tier.get("open_question", "")

    question_html = f'<div class="question">→ {question}</div>' if question else ""

    return f"""<div class="tier">
  <div class="tier-label">{label}</div>
  <h2>{headline}</h2>
  <div class="body">{body}</div>
  {question_html}
</div>
<hr class="divider">"""


def _render_signal_log_html(signals: list[dict]) -> str:
    if not signals:
        return ""

    items = []
    for i, s in enumerate(signals, 1):
        sig_type = s.get("signal_type", "unknown")
        headline = s.get("headline", "No headline")
        confidence = s.get("confidence", "?")
        weight = s.get("implication_weight", "?")
        source = s.get("source", "")
        implications = s.get("forward_implications", [])
        imp_html = ""
        if implications:
            imp_lines = "<br>".join(f"→ {imp}" for imp in implications[:3])
            imp_html = f'<div class="sig-imp">{imp_lines}</div>'

        items.append(f"""<div class="signal">
  <div class="sig-head">{i}. [{sig_type}] {headline}</div>
  <div class="sig-meta">Confidence: {confidence} | Weight: {weight} | Source: {source}</div>
  {imp_html}
</div>""")

    return f"""<div class="signal-log">
  <h3>Signal Log ({len(signals)} signals)</h3>
  {"".join(items)}
</div>"""


# ── Brief Rendering ─────────────────────────────────────────────────────

def render_brief(brief: dict, signals: list[dict] = None, findings: dict = None, run_date: date = None):
    """
    Render the daily brief as markdown, HTML, and PDF.
    Returns the path to the markdown file.
    """
    run_date = run_date or date.today()
    day_name = run_date.strftime("%A, %B %d, %Y")

    # ── Markdown ──
    md_path = _render_brief_md(brief, signals, findings, run_date, day_name)

    # ── HTML ──
    html_path = _render_brief_html(brief, signals, run_date, day_name)

    # ── PDF (from HTML) ──
    pdf_path = _render_pdf_from_html(html_path)

    return md_path


def _render_brief_md(brief, signals, findings, run_date, day_name):
    """Render brief as markdown."""
    lines = []
    lines.append(f"# The Morning Loaf — {day_name}")
    lines.append("")
    lines.append("---")
    lines.append("")

    for label, key in [("The Signal", "tier_1"), ("The Bullshit Flag", "tier_2"), ("Your World", "tier_3")]:
        tier = brief.get(key)
        lines.append(f"## {label}")
        lines.append("")
        if tier:
            lines.append(f"**{tier.get('headline', '')}**")
            lines.append("")
            lines.append(tier.get("body", ""))
            lines.append("")
            oq = tier.get("open_question")
            if oq:
                lines.append(f"→ *{oq}*")
                lines.append("")
        else:
            lines.append(f"*Nothing qualified today.*")
            lines.append("")
        lines.append("---")
        lines.append("")

    if signals:
        lines.append("## Signal Log")
        lines.append("")
        lines.append(f"*{len(signals)} signals ingested on {run_date.isoformat()}*")
        lines.append("")
        for i, s in enumerate(signals, 1):
            sig_type = s.get("signal_type", "unknown")
            headline = s.get("headline", "No headline")
            confidence = s.get("confidence", "?")
            weight = s.get("implication_weight", "?")
            source = s.get("source", "")
            lines.append(f"**{i}. [{sig_type}]** {headline}")
            lines.append(f"   Confidence: {confidence} | Weight: {weight} | Source: {source}")
            for imp in s.get("forward_implications", [])[:3]:
                lines.append(f"   → {imp}")
            lines.append("")

    if findings:
        finding_list = findings.get("findings", [])
        if finding_list:
            lines.append("---")
            lines.append("")
            lines.append("## Analysis Summary")
            lines.append("")
            for f in finding_list:
                f_type = f.get("type", "unknown")
                headline = f.get("headline", "")
                weight = f.get("implication_weight", "?")
                tier = f.get("tier_recommendation", "none")
                lines.append(f"**[{f_type}]** {headline}")
                lines.append(f"   Weight: {weight} | Tier: {tier}")
                reasoning = f.get("reasoning", "")
                if reasoning:
                    preview = reasoning[:300].replace("\n", " ")
                    if len(reasoning) > 300:
                        preview += "..."
                    lines.append(f"   Reasoning: {preview}")
                lines.append("")

    lines.append("---")
    lines.append("")
    lines.append(f"*Generated by Charlie at {datetime.now().strftime('%H:%M:%S')} on {day_name}*")

    md_path = config.briefs_dir / f"{run_date.isoformat()}.md"
    md_path.write_text("\n".join(lines))
    print(f"[Render] Brief markdown: {md_path}")
    return md_path


def _render_brief_html(brief, signals, run_date, day_name):
    """Render brief as styled HTML."""
    tiers_html = ""
    tiers_html += _render_tier_html("The Signal", brief.get("tier_1"))
    tiers_html += _render_tier_html("The Bullshit Flag", brief.get("tier_2"))
    tiers_html += _render_tier_html("Your World", brief.get("tier_3"))

    signal_log_html = _render_signal_log_html(signals) if signals else ""

    html = BRIEF_HTML_TEMPLATE.format(
        date=day_name,
        tiers=tiers_html,
        signal_log=signal_log_html,
        timestamp=datetime.now().strftime("%H:%M:%S"),
    )

    html_path = config.briefs_dir / f"{run_date.isoformat()}.html"
    html_path.write_text(html)
    print(f"[Render] Brief HTML: {html_path}")
    return html_path


def _render_pdf_from_html(html_path: Path):
    """Convert HTML to PDF using the system browser print or wkhtmltopdf if available."""
    pdf_path = html_path.with_suffix(".pdf")

    # Try wkhtmltopdf first
    try:
        subprocess.run(
            ["wkhtmltopdf", "--quiet", "--page-size", "Letter", str(html_path), str(pdf_path)],
            check=True, capture_output=True, timeout=30,
        )
        print(f"[Render] Brief PDF: {pdf_path}")
        return pdf_path
    except (FileNotFoundError, subprocess.CalledProcessError):
        pass

    # Try Chrome/Chromium headless
    for chrome in [
        "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome",
        "google-chrome",
        "chromium",
    ]:
        try:
            subprocess.run(
                [chrome, "--headless", "--disable-gpu", f"--print-to-pdf={pdf_path}", str(html_path)],
                check=True, capture_output=True, timeout=30,
            )
            print(f"[Render] Brief PDF: {pdf_path}")
            return pdf_path
        except (FileNotFoundError, subprocess.CalledProcessError):
            continue

    print(f"[Render] PDF skipped (install wkhtmltopdf or use Chrome to enable: brew install wkhtmltopdf)")
    return None


# ── Thesis Proposal Rendering ───────────────────────────────────────────

def render_thesis_proposal(proposal: dict):
    """
    Render a thesis update proposal as markdown, HTML, and PDF.
    Returns the path to the markdown file.
    """
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    proposed_at = proposal.get("proposed_at", datetime.now().isoformat())

    lines = []
    lines.append("# Thesis Update Proposal")
    lines.append("")
    lines.append(f"*Proposed: {proposed_at}*")
    lines.append("")
    lines.append(f"**Status: {proposal.get('status', 'pending_review')}**")
    lines.append("")

    summary = proposal.get("summary", "")
    if summary:
        lines.append("## Summary")
        lines.append("")
        lines.append(summary)
        lines.append("")

    confidence = proposal.get("confidence_assessment", "")
    if confidence:
        lines.append(f"**Overall confidence:** {confidence}")
        lines.append("")

    lines.append("---")
    lines.append("")

    # Extensions
    extensions = proposal.get("extensions", [])
    if extensions:
        lines.append("## Proposed Extensions")
        lines.append("")
        for i, ext in enumerate(extensions, 1):
            if isinstance(ext, dict):
                claim = ext.get("claim", ext.get("description", str(ext)))
                evidence = ext.get("evidence", "")
                conf = ext.get("confidence", "")
                lines.append(f"### Extension {i}")
                lines.append("")
                lines.append(f"**Claim:** {claim}")
                if evidence:
                    lines.append(f"**Evidence:** {evidence}")
                if conf:
                    lines.append(f"**Confidence:** {conf}")
                lines.append("")
            else:
                lines.append(f"**{i}.** {ext}")
                lines.append("")

    # Revisions
    revisions = proposal.get("revisions", [])
    if revisions:
        lines.append("---")
        lines.append("")
        lines.append("## Proposed Revisions")
        lines.append("")
        for i, rev in enumerate(revisions, 1):
            if isinstance(rev, dict):
                before = rev.get("before", rev.get("original_claim", ""))
                after = rev.get("after", rev.get("revised_claim", ""))
                reason = rev.get("reason", rev.get("rationale", ""))
                lines.append(f"### Revision {i}")
                lines.append("")
                if before:
                    lines.append(f"**Before:** {before}")
                if after:
                    lines.append(f"**After:** {after}")
                if reason:
                    lines.append(f"**Rationale:** {reason}")
                lines.append("")
            else:
                lines.append(f"**{i}.** {rev}")
                lines.append("")

    # New Patterns
    new_patterns = proposal.get("new_patterns", [])
    if new_patterns:
        lines.append("---")
        lines.append("")
        lines.append("## Emerging Patterns")
        lines.append("")
        for i, pattern in enumerate(new_patterns, 1):
            if isinstance(pattern, dict):
                desc = pattern.get("description", pattern.get("pattern", str(pattern)))
                ev = pattern.get("evidence", "")
                lines.append(f"**{i}. {desc}**")
                if ev:
                    lines.append(f"   Evidence: {ev}")
                lines.append("")
            else:
                lines.append(f"**{i}.** {pattern}")
                lines.append("")

    # Evidence Cited
    evidence_cited = proposal.get("evidence_cited", [])
    if evidence_cited:
        lines.append("---")
        lines.append("")
        lines.append("## Evidence Cited")
        lines.append("")
        for ev in evidence_cited:
            if isinstance(ev, dict):
                lines.append(f"- {ev.get('signal', ev.get('description', str(ev)))}")
            else:
                lines.append(f"- {ev}")
        lines.append("")

    # Watchlist Updates
    watchlist_updates = proposal.get("recommended_watchlist_updates", [])
    if watchlist_updates:
        lines.append("---")
        lines.append("")
        lines.append("## Recommended Watchlist Updates")
        lines.append("")
        for item in watchlist_updates:
            if isinstance(item, dict):
                lines.append(f"- **{item.get('entity', item.get('pattern', ''))}**: {item.get('reason', '')}")
            else:
                lines.append(f"- {item}")
        lines.append("")

    lines.append("---")
    lines.append("")
    lines.append(f"*Generated by Charlie at {datetime.now().strftime('%H:%M:%S')}*")

    # Write markdown
    md_path = config.thesis_dir / f"proposal_{timestamp}.md"
    md_path.write_text("\n".join(lines))
    print(f"[Render] Thesis proposal markdown: {md_path}")

    # Write HTML (reuse brief template structure)
    html_content = _thesis_to_html(lines, proposed_at)
    html_path = config.thesis_dir / f"proposal_{timestamp}.html"
    html_path.write_text(html_content)
    print(f"[Render] Thesis proposal HTML: {html_path}")

    # PDF
    _render_pdf_from_html(html_path)

    return md_path


def _thesis_to_html(md_lines: list[str], proposed_at: str) -> str:
    """Simple markdown-to-HTML conversion for thesis proposals."""
    body_parts = []
    for line in md_lines:
        if line.startswith("# "):
            body_parts.append(f"<h1>{line[2:]}</h1>")
        elif line.startswith("## "):
            body_parts.append(f"<h2>{line[3:]}</h2>")
        elif line.startswith("### "):
            body_parts.append(f"<h3>{line[4:]}</h3>")
        elif line.startswith("**") and line.endswith("**"):
            body_parts.append(f"<p><strong>{line[2:-2]}</strong></p>")
        elif line.startswith("- "):
            body_parts.append(f"<li>{line[2:]}</li>")
        elif line.startswith("---"):
            body_parts.append("<hr>")
        elif line.startswith("*") and line.endswith("*"):
            body_parts.append(f"<p><em>{line[1:-1]}</em></p>")
        elif line.strip():
            body_parts.append(f"<p>{line}</p>")

    body = "\n".join(body_parts)

    return f"""<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>Thesis Proposal — {proposed_at}</title>
<style>
  * {{ margin: 0; padding: 0; box-sizing: border-box; }}
  body {{ font-family: 'Georgia', serif; background: #fafafa; color: #1a1a1a; line-height: 1.6; }}
  .container {{ max-width: 640px; margin: 0 auto; padding: 40px 24px; }}
  h1 {{ font-size: 24px; border-bottom: 3px solid #1a1a1a; padding-bottom: 12px; margin-bottom: 24px; }}
  h2 {{ font-size: 18px; margin-top: 28px; margin-bottom: 12px; color: #2B3A4A; }}
  h3 {{ font-size: 15px; margin-top: 20px; margin-bottom: 8px; }}
  p {{ margin-bottom: 10px; font-size: 15px; }}
  li {{ margin-left: 24px; margin-bottom: 6px; font-size: 14px; }}
  hr {{ border: none; border-top: 1px solid #e0e0e0; margin: 24px 0; }}
  em {{ color: #666; }}
  @media print {{ body {{ background: white; }} .container {{ padding: 20px 0; }} }}
</style>
</head>
<body>
<div class="container">
{body}
</div>
</body>
</html>"""